name: "Setup Node with PNPM"
description: "Checkout, setup Node, configure PNPM and install dependencies"

inputs:
  node-version:
    description: "Node.js version"
    required: true
    default: "22"

  npm-token:
    description: "NPM token"
    required: false

runs:
  using: "composite"
  steps:
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 'latest'

    - name: Install Node
      uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-version }}
        cache: 'pnpm'
        cache-dependency-path: '**/pnpm-lock.yaml'
        registry-url: 'https://registry.npmjs.org'
        always-auth: true

    - name: Configure npm authentication
      if: ${{ inputs.npm-token != '' }}
      shell: bash
      run: |
        echo "//registry.npmjs.org/:_authToken=${{ inputs.npm-token }}" >> ~/.npmrc

#    - name: Get pnpm store directory
#      shell: bash
#      run: |
#        echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
#
#    - name: Setup pnpm cache
#      uses: actions/cache@v4
#      with:
#        path: ${{ env.STORE_PATH }}
#        key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
#        restore-keys: |
#          ${{ runner.os }}-pnpm-store-

    - name: Install dependencies
      shell: bash
      run: pnpm install
