name: build

on:
  push:
    branches:
      - main

jobs:
  build:
    if: github.repository == 'my-mcp-hub/mcp-kit'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install PNPM
        run: npm i pnpm@latest -g

      - name: Setup npmrc
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      - name: setup pnpm config
        run: pnpm config set store-dir $PNPM_CACHE_FOLDER

      - name: Install Package
        run: pnpm install

      - name: Build Package
        run: pnpm run build

      - name: Test Package
        run: pnpm run coverage

      - name: Coveralls
        uses: coverallsapp/github-action@v2
